[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
genai = "0.4.4"
openssl = "0.10.75"
postgres = "0.19.12"
postgres-openssl = "0.5.2"
rocket = "0.5.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
walkdir = "2.5.0"
